title: Sebastian Lukas Ahlstich
description: Academic website of Sebastian Lukas Ahlstich, PhD Fellow at Copenhagen Business School.
url: "https://ahlsebastian.github.io"
author: Sebastian L. Ahlstich
alternate_name: Sebastian Ahlstich
baseurl: ""
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: page


collections:
  research:
    output: false
    sort_by: order
  outreach:
    output: false
    sort_by: order